[perfcompare] Improve error when perfcompare.py is run with no arguments
Before this change, running perfcompare.py with no arguments
unhelpfully raises an exception:

  $ python3 ./src/testing/perfcompare/perfcompare.py
  ...
  AttributeError: 'Namespace' object has no attribute 'func'

The fix is to add required=True so that it prints a usage message
instead:

  $ python3 ./src/testing/perfcompare/perfcompare.py
  usage: perfcompare.py [-h] {compare_perf,run_local,validate_perfcompare} ...
  perfcompare.py: error: the following arguments are required: {compare_perf,run_local,validate_perfcompare}

This problem was introduced by switching to Python 3.  In Python 2,
add_subparsers() didn't take a "required" argument, and argparse would
give a "too few arguments" usage error if a subcommand wasn't given.

Change-Id: Ib7190c1e8d5af3fb8df8a4c7fa39ded7ff5c9e75
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/965156
Reviewed-by: Brian Hamrick <bhamrick@google.com>
Commit-Queue: Mark Seaborn <mseaborn@google.com>