[starnix] Add error context to major failure points in container startup
The built-in backtrace in a starnix kernel panic is pretty useless
since it doesn't show async stack trace and only starts at the point of
unwrap.

Adding some "with_context" calls makes it much easier to pin point where
did a PEER_CLOSED error happen. For example, we go from a single
"PEER_CLOSED" error without line numbers to the following:

  panicked at 'failed to start container: creating container "blabla", ../../src/starnix/kernel/execution/container.rs:235:38

  Caused by:
      0: mounting filesystems, ../../src/starnix/kernel/execution/container.rs:280:26
      1: creating filesystem from spec: [some path], ../../src/starnix/kernel/execution/container.rs:413:34
      2: create fd from metadata file, ../../src/starnix/kernel/fs/fuchsia/remote_bundle.rs:52:30
      3: PEER_CLOSED

Change-Id: Iffdddcd590a13e3f44fcc8cb82275dd2a027cdf2
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/883371
Fuchsia-Auto-Submit: Yifei Teng <yifeit@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Adam Perry <adamperry@google.com>