[starnix][vfs] fail `create_entry()` when path contains embedded '/'
When adding a node to the device registry, we expect to be able to
create nodes in subdirectories. E.g., `mapper/control`.

At present, this fails silently. That happens because
1. devtmpfs_create_device() doesn't have any special-case handling
   for embedded path separators.
2. DirEntry::create_entry() also lacks any special-case handling.

I think it's best to add special-case handling in devtmpfs, because
auto-magically handling embedded path separators isn't desirable
everywhere. E.g., `mkdir("foo/bar/baz")` should fail unless
`foo` and `bar` are already present.

In this CL, I update the VFS code to report an error when asked
to `create_entry()` with an embedded separator.

In a later CL, I'll update devtmpfs to special-case device names
with embedded separators.

Bug: b/310963779
Test: manual

Manual test
-----------
1. Revert https://fxrev.dev/958094
2. Boot image
3. Observe the following error in the system logs:
   ERROR: [src/starnix/kernel/device/registry.rs(305)] Cannot add device DeviceMetadata { bus: None, class: (Weak), name: [109, 97, 112, 112, 101, 114, 47, 99, 111, 110, 116, 114, 111, 108], device_type: DeviceType(2796), mode: Char } in devtmpfs (EINVAL (22), source: ../../src/starnix/kernel/vfs/dir_entry.rs:289:20, context: None)

Change-Id: Id002a08d862b26217fe41c903ef73b0df3f17927
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/957401
Reviewed-by: Guocheng Wei <guochengwei@google.com>
Fuchsia-Auto-Submit: Mukesh Agrawal <quiche@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>