[proc][uapi] remove --size_t-is-usize
Needed because of bindgen update to fix:

error: unexpected argument '--size_t-is-usize' found

(Similar to https://fxrev.dev/813826, but for uapi instead
of magma.)

Test: ran bindgen.py, observed minimal changes in output
Change-Id: I5cb270f4f79a781ad73d291e4a44c812bc973098
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/815471
Reviewed-by: Adam Barth <abarth@google.com>
Fuchsia-Auto-Submit: Mukesh Agrawal <quiche@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>