[audio] Add DAI support sketelon to virtual_audio
Also create a default PostToDispatcher() in VirtualAudioDriver and
a pure virtual dispatcher() used by PostToDispatcher().

Bug: 124865
Test: Switch to open DAI driver and back to a StreamConfig driver.
$ fx shell virtual_audio --dai --add --wait --stream --add --wait
Executing `--dai' command...
Then in another shell:
$ fx shell ls /dev/class/dai
8e73fc7a
And after pressing a key in the first shell
$ fx shell ls /dev/class/audio-output
7a29810f

Test: get-gain reports an error for DAI.
$ fx shell virtual_audio --add --get-gain --dai --add --get-gain
Executing `--add' command...
Executing `--get-gain' command...
--Received Gain   (mute: 0, agc: 0, gain: -0.75000 dB) for output
Executing `--dai' command...
Executing `--add' command...
Executing `--get-gain' command...
ERROR: Get gain failed

Change-Id: Ie7f61e66514e56ded8aa62fee1e8671143b8873b
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/832081
Commit-Queue: Andres Oportus <andresoportus@google.com>
Reviewed-by: Martin Puryear <mpuryear@google.com>