[weavestack] Avoid accessing uninitialized memory
... when converting between the various FIDL enums and Strings.

Strict FIDL enums are represented by a C++ "Enum Class". Traditionally,
enum classes are restricted to their fixed set of declared values;
however, they can also be zero-initialized using
"FooEnumClass my_enum = {}` syntax. This allows instances of the enum
class to exist outside of the set of declared values.

This leads to an unfortunate gap in the C++ compiler when writing a
function that switches on the enum value, and returns from each case.
The compiler requires that each predefined enum value is handled,
otherwise you'll get an error like the following:

error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]

However, it does not require the switch statement have a default case.
This allows one to write functions where some control paths don't have a
return value.

In Weavestack this is believed to manifest as Page Faults, because the
`AddressRemovalReasonToString()` will return an uninitialized
string_view when given a zero initialized address removal reason.

Bug: 136245

Change-Id: Iad3b84d926c35c1796b5ca0fe726117e7ee45708
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/955992
Reviewed-by: Prashanth Swaminathan <prashanthsw@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Jeff Martin <martinjeffrey@google.com>